### ISSUE TITLE
There should be a way to load animations or something similar while loading images

### ISSUE THREAD

**Issue by leon-marzahn** [jesusbotella/ngx-lazy-load-images#19]
I love this package and i use it regularly, but one big thing i don't like is, that with more latency between client and server, the client sometimes has to wait until the image is loaded.

I would appreciate if there would be a way to have an animation before it loads the images, or maybe load a low res image first.

**Comment by jesusbotella** [comment]
Hello @PsychoPflanze! Thank you for using this package!

I have always pointed in the previous issues that you can put a default `src` or `srcset` before loading the image to have a placeholder image before loading the proper one, but it is true that the image loading process might take a lot of time depending on the network.

I have thought about preloading the image before setting the proper src attribute so that the change happens instantly or almost instantly. Doing it that way you can have a placeholder src that will be replaced by the image src when the image is ready.

What do you think? Would that make the trick?

**Comment by PsychoPflanze** [comment]
Yes, that would do the trick! But i would prefer having another attribute ("placeholder-src" for example), so you have more separation :D

**Comment by lazysergey** [comment]
@jesusbotella also it would be useful to add class e.g. `loaded` when the image actually loads so we can fade it in with opacity

**Comment by jesusbotella** [comment]
Working on this right now. I'll keep you posted.

**Comment by cguasti** [comment]
this would be great, don't forget about the images that are in backgrounds..

**Comment by arturhun** [comment]
@jesusbotella 
Any progress on this?
What if there was another directive which would turn off its host when the image was ready?
1. **`img`** 

```html
<img [attr.data-src]="img"/>
<my-skeleton lazy-load-images-placeholder></my-skeleton>
```

2. **`background-image`**

```html
<div [attr.data-background-src]="img">
  <my-skeleton lazy-load-images-placeholder></my-skeleton>
</div>
```

**Comment by Meistercoach83** [comment]
Hey there! Would be great if a placeholder or a loading-indicator could be used - and after the (background)-image is loaded, the placeholder or indicator is hidden.

**Comment by jesusbotella** [comment]
It's been a while since this issue is opened. Not sure if feature request still stands.
Please post a comment if you still want this.
