### ISSUE TITLE
getting errors

### ISSUE THREAD

**Issue by alexthelion** [jesusbotella/ngx-lazy-load-images#20]
Hi,

I'm getting errors, with the following code:

```
<div class="row" *ngIf="isLoadingFinished()">
  <div *ngFor="let item of items | SortItemsByTitlePipe; let i = index" class="col-lg-4 col-md-6 col-sm-6 col-xs-12" lazy-load-images>
    <img *ngIf="item.images[0] != null" data-src="http://peacefultomorrows.org/wp-content/uploads/2016/06/two-doves.png"
         width="150px" height="150px" class="image-style">
  </div>
</div>
```

> A bad HTTP response code (404) was received when fetching the script.
> 
> Failed to load resource: net::ERR_INVALID_RESPONSE

**Comment by jesusbotella** [comment]
Hello @alexthelion!

I am afraid that this error is not caused by the image lazy loading. There should be a link to the right of that message that points to the script that caused the error.

Please feel free to comment if you think I am wrong, or provide any example where I can test that failing behaviour :)
